#!/bin/bash

echo "Syncing the pre-push hook"
cd "$(git rev-parse --show-toplevel)"
cp git-hooks/pre-push .git/hooks/pre-push 

echo "Running tests"
python -m unittest 

echo "Pre-push checks completed."