"""Render the scanned pipeline as the README's mermaid diagram.

Run it to rewrite the block between the markers in README.md; run it with
`--check` to fail when that block is out of date. The check is what makes the
diagram trustworthy: a hook or workflow can't change without the picture
changing with it.

This module only draws. Everything it knows comes from `pipeline_scan.scan`,
which is also what the gate tests assert against -- so the diagram and the
tests cannot disagree about what the pipeline does.

    python scripts/pipeline_diagram.py           # rewrite README.md
    python scripts/pipeline_diagram.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
# Importable both as `python scripts/pipeline_diagram.py` (how the hook calls
# it) and as `python -m scripts.pipeline_diagram` (how the tests import it).
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.pipeline_scan import Group, Stage, scan  # noqa: E402
# Its own file, wholly machine-owned. It used to be a marked region inside
# README.md, which meant every regeneration rewrote a file full of hand-written
# prose -- one bad regex away from eating it. A generated artifact should own
# its file; the README links to it.
OUTPUT = PROJECT_ROOT / "docs" / "pipeline.md"

# The README gets a second, smaller rendering of the same model: the shape of
# the pipeline, without the per-command detail. Two views, one scan, so they
# cannot disagree. This one *is* a marked region inside hand-written prose,
# which is why it is replaced by an exact-match splice and nothing else.
README = PROJECT_ROOT / "README.md"
START = "<!-- pipeline:start -->"
END = "<!-- pipeline:end -->"

HEADER = """# Deployment Pipeline

<!-- Generated by scripts/pipeline_diagram.py from the git hooks, the workflow
     files and the command guard's rules. Do not edit by hand: .githooks/post-commit
     regenerates it in a follow-up commit whenever it goes stale. -->

Everything from a command an agent proposes to the live site.

- **•** a step that stops the pipeline when it fails
- **◦** a step that only reports
- a dashed box never blocks anything
"""

TITLES = {
    Group.AGENT: "Agent",
    Group.COMMIT: "git commit",
    Group.PUSH: "git push",
    Group.CI: "CI — on push to main",
    Group.PR: "CI — on pull request",
    Group.SCHEDULED: "Scheduled",
}

# The spine: each of these leads into the next. PR and scheduled work hang off
# to the side -- they gate nothing on the way to production.
SPINE = [Group.AGENT, Group.COMMIT, Group.PUSH, Group.CI]

LIVE = "live"

# Long enough that the hooks' commands fit whole. Shorter and it truncates the
# end of the line, which is exactly where the meaning is: `ensure_server.py
# post-push` and `ensure_server.py pre-push` differ only in the part a short
# cut-off throws away.
MAX_LABEL = 80


def render(stages: list[Stage]) -> str:
    """The full README block: banner, fence, graph."""
    lines = ["```mermaid", "graph TD"]
    grouped = {group: [s for s in stages if s.group is group] for group in Group}

    for group in Group:
        members = grouped[group]
        if not members:
            continue
        lines.append(f'    subgraph {group.value}["{TITLES[group]}"]')
        lines += [f"        {_node(stage)}" for stage in members]
        lines.append("    end")

    if any(stage.deploys for stage in stages):
        lines.append(f'    {LIVE}(["Live site"])')

    lines += [f"    {edge}" for edge in _edges(stages, grouped)]
    lines += _styles(stages)
    lines.append("```")
    return HEADER + "\n" + "\n".join(lines) + "\n"


def render_overview(stages: list[Stage]) -> str:
    """One box per phase, naming what is in it. No commands.

    The README's job is to show the shape and hand you the link; the detail
    belongs in docs/pipeline.md, one click away.
    """
    grouped = {group: [s for s in stages if s.group is group] for group in Group}
    lines = ["```mermaid", "graph LR"]

    present = [group for group in SPINE if grouped[group]]
    for group in present:
        members = ", ".join(_escape(s.name) for s in grouped[group])
        gates = sum(1 for s in grouped[group] if s.blocks)
        suffix = "" if gates == len(grouped[group]) else f" ({gates} of {len(grouped[group])} gate)"
        lines.append(
            f'    {group.value}["<b>{TITLES[group]}</b><br/>{members}{suffix}"]'
        )
    lines += [
        f"    {a.value} --> {b.value}" for a, b in zip(present, present[1:])
    ]
    if any(s.deploys for s in stages) and present:
        lines.append(f"    {present[-1].value} --> {LIVE}([Live site])")
    lines.append("```")
    return "\n".join(lines)


def _node(stage: Stage) -> str:
    """One box: what it is, and where to read what it does.

    Deliberately not the commands. A CI job runs six of them, and six lines of
    shell in a box is a wall rather than a diagram -- the point here is the
    shape of the pipeline and where each part is declared. The source path is
    on the box precisely so the detail is one click away.

    The exception is a hook whose steps disagree about gating: that difference
    is the thing worth seeing, so it is drawn.
    """
    # For a hook the name *is* the file name; for a CI job it is the job, and
    # bolding the workflow file instead would title five boxes "deploy.yml".
    parts = [f"<b>{_escape(stage.name)}</b>", f"<i>{_escape(stage.source)}</i>"]
    if _detailed(stage):
        parts.append("runs:")
        for step in stage.steps:
            bullet = "•" if step.blocks else "◦"
            parts.append(f"{bullet} {_escape(_shorten(step.command))}")
    elif not stage.blocks:
        parts.append("<i>reports, does not block</i>")
    # Mermaid centres label lines; a list of shell commands only reads as a
    # list when its bullets line up, hence the explicit left alignment.
    body = "<br/>".join(parts)
    return f'{_id(stage.key)}["<div style=\'text-align:left\'>{body}</div>"]'


def _detailed(stage: Stage) -> bool:
    """Git hooks list what they call; CI jobs don't.

    A hook is a few lines of shell you'd otherwise have to open the file to
    read, and which of them gate differs line by line. A CI job is a dozen
    setup steps whose detail is noise at this altitude -- its box carries the
    workflow path instead, and GitHub renders that file better than a diagram
    box ever will.
    """
    return stage.group in (Group.COMMIT, Group.PUSH) and bool(stage.steps)


def _edges(stages: list[Stage], grouped: dict[Group, list[Stage]]) -> list[str]:
    """Spine first, then each job's declared `needs:`, then the deploy."""
    edges = []
    for earlier, later in zip(SPINE, SPINE[1:]):
        source, target = grouped[earlier], grouped[later]
        if source and target:
            # Into the first node of the next phase; `needs:` fans out from there.
            entry = [s for s in target if not s.needs] or target
            edges += [
                f"{_id(source[-1].key)} --> {_id(node.key)}" for node in entry
            ]

    for stage in stages:
        for need in stage.needs:
            required = _resolve(stages, stage, need)
            if required:
                edges.append(f"{_id(required.key)} --> {_id(stage.key)}")

    edges += [
        f"{_id(stage.key)} --> {LIVE}" for stage in stages if stage.deploys
    ]
    return edges


def _resolve(stages: list[Stage], stage: Stage, need: str) -> Stage | None:
    """`needs:` names a job in the same workflow file, not a global id."""
    for candidate in stages:
        if candidate.source == stage.source and candidate.name == need:
            return candidate
    return None


def _styles(stages: list[Stage]) -> list[str]:
    """Dash the boxes that report rather than gate."""
    reporting = [_id(s.key) for s in stages if not s.blocks]
    if not reporting:
        return []
    return [
        "    classDef reports stroke-dasharray: 4 3",
        f"    class {','.join(reporting)} reports",
    ]


def _id(key: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", key)


# `"` ends a quoted label; `|` delimits edge labels; braces open a node shape.
# All four appear in real commands here (`curl -w "%{http_code}"`, the guard's
# alternations), so none of them can be left raw.
# Mermaid's own escapes (#nn;), NOT HTML entities. GitHub decodes `&quot;`
# back into a real `"` before the parser sees it, which ends the quoted label
# early -- that broke the whole graph. A double quote is replaced rather than
# escaped, because nothing in a command label needs to be one.
# `&` is first: escaping it after the others would mangle their output.
ESCAPES = {
    '"': "'",
    "<": "#60;",
    "|": "#124;",
    "{": "#123;",
    "}": "#125;",
}
# Deliberately NOT escaped: `&` and `>`. Both are harmless inside a label, and
# escaping them turned `>/dev/null 2>&1` into `#62;/dev/null 2#62;#38;1`, which
# is not a thing anyone can read. A diagram nobody can read has failed whatever
# else it gets right.


def _escape(text: str) -> str:
    for char, replacement in ESCAPES.items():
        text = text.replace(char, replacement)
    return text


def _shorten(command: str) -> str:
    return command if len(command) <= MAX_LABEL else command[: MAX_LABEL - 1] + "…"


def _readme_block(overview: str) -> str:
    return f"{START}\n{overview}\n{END}"


def is_current(document: str, overview: str) -> bool:
    return (
        OUTPUT.exists()
        and OUTPUT.read_text() == document
        and _readme_block(overview) in README.read_text()
    )


def update(document: str, overview: str) -> bool:
    """Write both renderings. Returns whether anything changed."""
    changed = False

    if not OUTPUT.exists() or OUTPUT.read_text() != document:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(document)
        changed = True

    text = README.read_text()
    block = _readme_block(overview)
    if block not in text:
        if START not in text or END not in text:
            raise SystemExit(
                f"README.md has no {START} / {END} markers, so there is "
                f"nowhere to put the overview."
            )
        README.write_text(
            re.sub(
                re.escape(START) + r".*?" + re.escape(END),
                lambda _: block,
                text,
                flags=re.DOTALL,
            )
        )
        changed = True

    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the diagram is out of date, changing nothing",
    )
    args = parser.parse_args(argv)

    stages = scan(PROJECT_ROOT)
    document, overview = render(stages), render_overview(stages)

    if args.check:
        if is_current(document, overview):
            return 0
        print(
            "The pipeline diagram is out of date -- the hooks or workflows "
            "changed without it.\n\n"
            "    python scripts/pipeline_diagram.py\n",
            file=sys.stderr,
        )
        return 1

    print("Updated." if update(document, overview) else "Already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
