"""Render the scanned pipeline as the README's mermaid diagram.

Run it to rewrite the block between the markers in README.md; run it with
`--check` to fail when that block is out of date. The check is what makes the
diagram trustworthy: a hook or workflow can't change without the picture
changing with it.

This module only draws. Everything it knows comes from `pipeline_scan.scan`,
which is also what the gate tests assert against -- so the diagram and the
tests cannot disagree about what the pipeline does.

    python scripts/pipeline_diagram.py           # rewrite README.md
    python scripts/pipeline_diagram.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
# Importable both as `python scripts/pipeline_diagram.py` (how the hook calls
# it) and as `python -m scripts.pipeline_diagram` (how the tests import it).
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.pipeline_scan import Group, Stage, scan  # noqa: E402
README = PROJECT_ROOT / "README.md"

START = "<!-- pipeline:start -->"
END = "<!-- pipeline:end -->"

# Generated between the markers, so an edit here is an edit to the README.
BANNER = (
    "<!-- Generated by scripts/pipeline_diagram.py from the hooks and\n"
    "     workflows themselves. Do not edit by hand: pre-commit regenerates\n"
    "     this whenever it goes stale. -->"
)

TITLES = {
    Group.AGENT: "Agent",
    Group.COMMIT: "git commit",
    Group.PUSH: "git push",
    Group.CI: "CI — on push to main",
    Group.PR: "CI — on pull request",
    Group.SCHEDULED: "Scheduled",
}

# The spine: each of these leads into the next. PR and scheduled work hang off
# to the side -- they gate nothing on the way to production.
SPINE = [Group.AGENT, Group.COMMIT, Group.PUSH, Group.CI]

LIVE = "live"
MAX_LABEL = 44


def render(stages: list[Stage]) -> str:
    """The full README block: banner, fence, graph."""
    lines = ["```mermaid", "graph TD"]
    grouped = {group: [s for s in stages if s.group is group] for group in Group}

    for group in Group:
        members = grouped[group]
        if not members:
            continue
        lines.append(f'    subgraph {group.value}["{TITLES[group]}"]')
        lines += [f"        {_node(stage)}" for stage in members]
        lines.append("    end")

    if any(stage.deploys for stage in stages):
        lines.append(f'    {LIVE}(["Live site"])')

    lines += [f"    {edge}" for edge in _edges(stages, grouped)]
    lines += _styles(stages)
    lines.append("```")
    return f"{BANNER}\n\n" + "\n".join(lines)


def _node(stage: Stage) -> str:
    """One box: what it is, and where to read what it does.

    Deliberately not the commands. A CI job runs six of them, and six lines of
    shell in a box is a wall rather than a diagram -- the point here is the
    shape of the pipeline and where each part is declared. The source path is
    on the box precisely so the detail is one click away.

    The exception is a hook whose steps disagree about gating: that difference
    is the thing worth seeing, so it is drawn.
    """
    parts = [f"<b>{_escape(stage.name)}</b>", f"<i>{_escape(stage.source)}</i>"]
    if _mixed(stage):
        for step in stage.steps:
            parts.append(
                ("" if step.blocks else "◦ ") + _escape(_shorten(step.command))
            )
    elif not stage.blocks:
        parts.append("<i>reports, does not block</i>")
    return f'{_id(stage.key)}["{"<br/>".join(parts)}"]'


def _mixed(stage: Stage) -> bool:
    """Does this stage both gate and report? That is worth spelling out."""
    return len({step.blocks for step in stage.steps}) > 1


def _edges(stages: list[Stage], grouped: dict[Group, list[Stage]]) -> list[str]:
    """Spine first, then each job's declared `needs:`, then the deploy."""
    edges = []
    for earlier, later in zip(SPINE, SPINE[1:]):
        source, target = grouped[earlier], grouped[later]
        if source and target:
            # Into the first node of the next phase; `needs:` fans out from there.
            entry = [s for s in target if not s.needs] or target
            edges += [
                f"{_id(source[-1].key)} --> {_id(node.key)}" for node in entry
            ]

    for stage in stages:
        for need in stage.needs:
            required = _resolve(stages, stage, need)
            if required:
                edges.append(f"{_id(required.key)} --> {_id(stage.key)}")

    edges += [
        f"{_id(stage.key)} --> {LIVE}" for stage in stages if stage.deploys
    ]
    return edges


def _resolve(stages: list[Stage], stage: Stage, need: str) -> Stage | None:
    """`needs:` names a job in the same workflow file, not a global id."""
    for candidate in stages:
        if candidate.source == stage.source and candidate.name == need:
            return candidate
    return None


def _styles(stages: list[Stage]) -> list[str]:
    """Dash the boxes that report rather than gate."""
    reporting = [_id(s.key) for s in stages if not s.blocks]
    if not reporting:
        return []
    return [
        "    classDef reports stroke-dasharray: 4 3",
        f"    class {','.join(reporting)} reports",
    ]


def _id(key: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", key)


# `"` ends a quoted label; `|` delimits edge labels; braces open a node shape.
# All four appear in real commands here (`curl -w "%{http_code}"`, the guard's
# alternations), so none of them can be left raw.
ESCAPES = {
    "&": "&amp;",
    '"': "&quot;",
    "<": "&lt;",
    ">": "&gt;",
    "|": "&#124;",
    "{": "&#123;",
    "}": "&#125;",
}


def _escape(text: str) -> str:
    for char, replacement in ESCAPES.items():
        text = text.replace(char, replacement)
    return text


def _shorten(command: str) -> str:
    return command if len(command) <= MAX_LABEL else command[: MAX_LABEL - 1] + "…"


def update(readme: Path, block: str) -> bool:
    """Replace the marked block. Returns whether anything changed."""
    text = readme.read_text()
    if START not in text or END not in text:
        raise SystemExit(
            f"{readme.name} has no {START} / {END} markers, so there is "
            f"nowhere to put the diagram."
        )
    replacement = f"{START}\n{block}\n{END}"
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: replacement,
        text,
        flags=re.DOTALL,
    )
    if updated == text:
        return False
    readme.write_text(updated)
    return True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the README diagram is out of date, changing nothing",
    )
    parser.add_argument(
        "--fix-or-fail",
        action="store_true",
        help="regenerate a stale diagram, then exit non-zero so it can be reviewed",
    )
    args = parser.parse_args(argv)

    block = render(scan(PROJECT_ROOT))
    current = f"{START}\n{block}\n{END}" in README.read_text()

    if args.check:
        if current:
            return 0
        print(
            "README.md's pipeline diagram is out of date -- the hooks or "
            "workflows changed without it.\n\n"
            "    python scripts/pipeline_diagram.py\n",
            file=sys.stderr,
        )
        return 1

    if args.fix_or_fail:
        # For the pre-commit hook. The diagram is derived, so being stale is
        # never a judgement call -- fix it. It is deliberately not staged:
        # `git add README.md` would sweep in unrelated README edits this
        # commit was never meant to carry. So stop once, and let the next
        # commit take it.
        if current:
            return 0
        update(README, block)
        print(
            "README.md's pipeline diagram was stale and has been regenerated "
            "from the hooks and workflows.\nReview it, stage it, and commit "
            "again.",
            file=sys.stderr,
        )
        return 1

    print("README.md updated." if update(README, block) else "Already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
